---
title: "COVID-19 World and US View"
description: |
  Stay home, safe a life.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
install.load::install_load(c('distill','dplyr', 'tidyverse', 'ggplot2', 'plotly', 'rmarkdown', 'magrittr', 'RCurl', 'lubridate', 'DT', 'ggthemes', 'zoo'))
```

This main page is a dashboard being built, which may be refreshed in the future. **Last updated `r format(lubridate::now("US/Pacific"), '%a, %b %d %I:%M %p')`** PST.

See "Analyses" tab for analyses performed.

## World View
```{r}


read_covid <- function(url, var){
  df <- read_csv(url) %>%
    filter(Country_Region == 'US') %>%
    select(-UID, -FIPS, -iso2, -iso3, -code3, -Admin2, -Lat, -Long_, -Combined_Key) 
  
  # Dead has population, confirmed doesn't
  if (var == 'confirmed'){
    df %<>% gather(date_raw, value, -`Province_State`, -`Country_Region`)  %>%
      mutate(date = mdy(date_raw)) %>%
      group_by(Province_State, date) %>%
      summarize(value = sum(value))
  } else {
    df %<>% gather(date_raw, value, -Population, -`Province_State`, -`Country_Region`)  %>%
    mutate(date = mdy(date_raw)) %>%
    group_by(Province_State, date) %>%
    summarize(value = sum(value),
              Population = sum(Population))
  }
  df[var] = df$value
  df %<>% select(-value)
  
  # Clean column names
  colnames(df) %<>% 
    tolower() %>% 
    str_replace_all(fixed('/'), '_') %>%
    str_replace_all(fixed(' '), '_')
  
  return(df)
}

# Read in data
url_conf = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv'
url_dead = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv'
df <- read_covid(url_conf, 'confirmed') %>%
  left_join(read_covid(url_dead, 'dead')) %>% 
  group_by(province_state) %>%
  arrange(province_state, date) %>%
  mutate(new = (confirmed - lag(confirmed))/10,
         dead = dead - lag(dead),
         new14 = lag(new, 14),
         new_ma = rollmean(new, k=7, fill = NA, align='right'),
         dead_ma = rollmean(dead, k=7, fill=NA, align='right'),
         new14_ma = rollmean(new14, k=7, fill=NA, align='right')) %>%
  filter(date > Sys.Date() - 45) %>%
  ungroup()

df_us = read_covid(url_conf, 'confirmed') %>%
  left_join(read_covid(url_dead, 'dead')) %>% 
  group_by(date) %>%
  summarize(confirmed = sum(confirmed),
            dead = sum(dead),
            population=sum(population)) %>%
  mutate(new = (confirmed - lag(confirmed))/10,
         dead = dead - lag(dead),
         new14 = lag(new, 14),
         new_ma = rollmean(new, k=7, fill=NA, align='right'),
         dead_ma = rollmean(dead, k=7, fill=NA, align='right'),
         new14_ma = rollmean(new14, k=7, fill=NA, align='right')) %>%
  filter(date > Sys.Date() - 60) %>%
  ungroup()

cor(df$new14, df$dead, use='complete.obs')

ggplot2::theme_set(theme_minimal())
```

```{r}
plot_trends <- function(df_tmp, title) {
  colors = palette_pander(2) 
  
  df1 <- df_tmp %>% select(date, new14, new14_ma)
  df2 <- df_tmp %>% select(date, dead, dead_ma)
  
  p <- ggplot() + 
    geom_point(data=df1, aes(x=date, y=new14), alpha=.5, color=colors[1]) +
    geom_line(data=df1, aes(x=date, y=new14_ma), color=colors[1]) +
    geom_point(data=df2, aes(x=date, y=dead), alpha=.5, color=colors[2]) +
    geom_line(data=df2, aes(x=date, y=dead_ma), color=colors[2]) +
    labs(title=title, y='', x='') + 
    scale_x_date(labels = scales::date_format("%m/%d")) 
  # Attempt to add legend
  # scale_color_identity(guide='legend')
  # scale_color_identity(name='Points', guide='legend',
                       # # labels=c('a', 'b'), 
                       # values=c('red'=colors[1], 'black'=colors[2]))
                       # breaks=colors)
                     # values=c(colors[1], colors[2]),
                     # labels=c('a', 'b'))
  return(p)
}
```
# US
```{r}
plot_trends(df_us, 'US')
```

# States
```{r}
states = df$province_state %>% unique() %>% sort()
for (state in states){
  df_tmp <- df %>% filter(province_state == !!state) 
  p <- plot_trends(df_tmp, title=state)
  # print(ggplotly(p))
  print(p)
}

  
```

